### ISSUE TITLE
Lack of interactivity

### ISSUE THREAD

**Issue by danieleguido** [CVCEeu-dh/histograph#17]
##### similarity computation
- [x]  backend improve [/api/cooccurrences](http://localhost:8000/api/cooccurrences) (avg timing: 1.71 sec)
  
  ```
  node scripts\manage.js --task=query --cypher=resource/get_cooccurrences
       --limit=500 --offset=0
  ```
- [ ]  fronted, cfr. [sigmajs directive](../blob/master/client/src/js/directives/sigma.js) e.g. in [index](http://localhost:8000/)
- [x] similarity measure based on jaccard distance - once taken into account the **tfidf** property for each `(entity)-(resource)` relationship. check
  
  ```
  node scripts\manage.js --task=query --cypher=playground/jaccard_similarity
       --limit=100 --offset=0 --id=1088
  ```
##### improve search (lucene)
- [x]  tuning neo4j/lucene autoindex parameters, tune neo4j memory params
- [x]  check lucene query for multiple words (performances and lucene syntax for OR / AND) and order by search result retrieval score or other sorting order ([automatic index?](http://neo4j.com/docs/stable/auto-indexing.html)):
  
  ```
   node scripts\manage.js --task=query --cypher=suggest/get_matching_resources
        --query=full_search:*helmut*kohl* --limit=10 --offset=0
  
  After having build the lucene index of the correct type, you can do this:
  
  node scripts/manage.js --task=query --cypher=suggest/get_matching_resources 
       --query="full_search:\"helmut kohl\"" --limit=10 --offset=0
  ```
- How to sort the results?
- How to get rid of wild card search?
- How to get query time of ~300 ms down.

Lucene query cfr. one of these [lucene query parser](https://www.npmjs.com/search?q=lucene)
##### timeline clustering / display
- [x]  better timeline clustering /api/resource/2084/related/resource/graph?limit=100
- [x]  tuning neo4 index parameters (start_time, end_time)
- [ ]  fronted  cfr. [timeline directive](../blob/master/client/src/js/directives/timeline.js) e.g. in [index](http://localhost:8000/)
##### other: production mode
- [x]  angular template loading and parsing
- [x]  minify

In order to test specific queries, [manage.js](https://github.com/CVCEeu-dh/histograph/blob/master/scripts/manage.js) script takes the `exectime` of every query execution. Cypher query arguments should be passed via command line as they were scripts argument, while the special argument `--cypher` takes a pseudo path, e.g:

```
node scripts\manage.js --task=query --cypher=playground/demo --limit=10 --offset=0
```

where ´playground´ is a [cypher file](https://github.com/CVCEeu-dh/histograph/blob/master/queries/playground.cyp) without the extension and `demo` is a _named_ query inside that file cfr [decypher doc](https://github.com/Yomguithereal/decypher)

**Comment by danieleguido** [comment]
timeline clustering on month, with neo4j indexes:

```
// name: create_index_on_start_time
// create index on start date to group / filter result by timestamp
CREATE INDEX ON :resource(start_time)

// name: create_index_on_start_month
// create index on start date to group / filter result by date
CREATE INDEX ON :resource(start_month)

// name: create_index_on_end_time
// create index on start date to group / filter result by date
CREATE INDEX ON :resource(end_time)

// name: create_index_on_end_month
// create index on start date to group / filter result by date
CREATE INDEX ON :resource(end_month)
```

**Comment by bbroeksema** [comment]
@danieleguido Did you measure if it resulted in any improvements?

**Comment by danieleguido** [comment]
@bbroeksema the execution query time is now 0.18s (it was 0.78s) and the server clustering simplifies a lot the construction of the timeline in the client.

**Comment by bbroeksema** [comment]
To get a working lucene index:
1. rm -rf data/graph.db/index\* (this removes a directory and a db file)
2. Create a new index by following the instructions here: http://jexp.de/blog/2014/03/full-text-indexing-fts-in-neo4j-2-0/
3. Don't forget to rebuild the query by performing the match and reset the indexed properties.

**Comment by danieleguido** [comment]
@bbroeksema I find a better and cleaner approach in SO for the lucene node_auto_index http://stackoverflow.com/a/29174440/4004419
